import {NextResponse} from 'next/server';
export const dynamic='force-dynamic'; export const revalidate=0;
const SHEET_ID=process.env.GOOGLE_SHEET_ID||'1yhtm8pTJ9VP0TUrFm2JedYoCZ_M22K196luw3u9Xl4s';
const GID=process.env.GOOGLE_SHEET_GID||'946404240';
const aliases={timestamp:['timestamp','date/time','datetime'],concern:['concern group','concern_group','concern'],province:['province'],municipality:['municipality','city/municipality','city'],facility:['facility'],restored:['date restored','restored date'],status:['final status','final_status','status'],rfo:['rfo','ops team','team','assigned team'],endorsed:['date endorsed','endorsed date'],ageing:['ageing','aging'],sla:['sla','sla status']};
const norm=s=>String(s??'').trim().toLowerCase().replace(/\s+/g,' ');
function headers(h){const n=h.map(norm),o={};for(const[k,a]of Object.entries(aliases))o[k]=n.findIndex(x=>a.includes(x));return o}
function csv(t){const rows=[];let row=[],cell='',q=false;for(let i=0;i<t.length;i++){const c=t[i],n=t[i+1];if(c==='"'&&q&&n==='"'){cell+='"';i++;continue}if(c==='"'){q=!q;continue}if(c===','&&!q){row.push(cell);cell='';continue}if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(cell);cell='';if(row.some(v=>v!==''))rows.push(row);row=[];continue}cell+=c}if(cell||row.length){row.push(cell);if(row.some(v=>v!==''))rows.push(row)}return rows}
function dt(v){if(v instanceof Date&&!isNaN(v))return v;const s=String(v||'').trim();if(!s)return null;const d=new Date(s);return isNaN(d)?null:d}
function clean(raw){if(!raw.length)return{rows:[],quality:{issues:0}};const h=raw[0],c=headers(h),out=[],issues=[];for(let i=1;i<raw.length;i++){const r=raw[i];if(!r.some(v=>String(v).trim()))continue;const status=String(c.status>=0?r[c.status]:'').trim().toUpperCase()||'UNKNOWN',province=String(c.province>=0?r[c.province]:'').trim()||'Unspecified',concern=String(c.concern>=0?r[c.concern]:'').trim()||'Unspecified',rfo=String(c.rfo>=0?r[c.rfo]:'').trim()||'Blank';const start=dt(c.endorsed>=0?r[c.endorsed]:c.timestamp>=0?r[c.timestamp]:''),restored=dt(c.restored>=0?r[c.restored]:''),rawAge=c.ageing>=0?String(r[c.ageing]??''):'';let hours=null,m=rawAge.match(/\d+(?:\.\d+)?/);if(m)hours=Number(m[0])*24;else if(start)hours=((status==='RESTORED'&&restored?restored:new Date())-start)/3600000;let sla=String(c.sla>=0?r[c.sla]:'').trim().toLowerCase();if(!sla)sla=hours==null?'Unknown':hours<=24?'1. within 24 hrs':hours<=48?'2. within 48 hrs':'3. beyond 48 hrs';else if(sla.includes('beyond'))sla='3. beyond 48 hrs';else if(sla.includes('48'))sla='2. within 48 hrs';else if(sla.includes('24'))sla='1. within 24 hrs';const open=!['RESTORED','DUPLICATED','CLOSED'].includes(status);if(!start)issues.push('Missing endorsement/timestamp row '+(i+1));if(status==='UNKNOWN')issues.push('Missing final status row '+(i+1));out.push({province,concern,rfo,status,sla,open,endorsedDate:start?start.toISOString().slice(0,10):'',restored24:!!restored&&Date.now()-restored.getTime()<=86400000&&restored<=new Date(),new24:!!start&&Date.now()-start.getTime()<=86400000&&start<=new Date()})}return{rows:out,quality:{issues:issues.length,samples:issues.slice(0,8)}}}
export async function GET(){try{const u='https://docs.google.com/spreadsheets/d/'+encodeURIComponent(SHEET_ID)+'/gviz/tq?tqx=out:csv&gid='+encodeURIComponent(GID),r=await fetch(u,{cache:'no-store'});if(!r.ok)throw new Error('Google Sheets returned HTTP '+r.status);const t=await r.text();if(t.includes('<html'))throw new Error('Google Sheets did not return CSV. Check sharing/access settings.');const d=clean(csv(t)),unique=k=>[...new Set(d.rows.map(x=>x[k]).filter(Boolean))].sort();return NextResponse.json({rows:d.rows,options:{province:unique('province'),status:unique('status'),rfo:unique('rfo'),concern:unique('concern')},quality:d.quality,fetchedAt:new Date().toISOString()})}catch(e){return NextResponse.json({error:e.message},{status:500})}}
