'use client';
import {useEffect,useMemo,useState} from 'react';
import {AreaChart,Area,BarChart,Bar,PieChart,Pie,Cell,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer} from 'recharts';
const REFRESH_MS=60000;
const fmt=n=>new Intl.NumberFormat('en-US').format(n||0);
function Select({label,value,onChange,options}){return <label className="filter"><span>{label}</span><select value={value} onChange={e=>onChange(e.target.value)}><option>All</option>{options.filter(Boolean).map(v=><option key={v}>{v}</option>)}</select></label>}
function Card({title,value,note,accent}){return <div className="card" style={{'--accent':accent}}><div className="card-label">{title}</div><div className="card-value">{fmt(value)}</div><div className="card-note">{note}</div></div>}
function Panel({title,subtitle,children}){return <section className="panel"><div className="panel-head"><h2>{title}</h2><p>{subtitle}</p></div>{children}</section>}
function Donut({data,colors}){return <div className="chart-wrap"><ResponsiveContainer width="100%" height={230}><PieChart><Pie data={data} dataKey="value" nameKey="name" innerRadius={62} outerRadius={88} paddingAngle={2}>{data.map((_,i)=><Cell key={i} fill={colors[i%colors.length]}/>)}</Pie><Tooltip contentStyle={{background:'#0c1628',border:'1px solid #23334f'}}/></PieChart></ResponsiveContainer><div className="legend">{data.map((x,i)=><div key={x.name}><i style={{background:colors[i%colors.length]}}/>{x.name}<b>{fmt(x.value)}</b></div>)}</div></div>}
export default function Dashboard(){
 const [p,setP]=useState(null),[f,setF]=useState({province:'All',status:'All',rfo:'All',concern:'All'}),[last,setLast]=useState(null),[error,setError]=useState('');
 async function load(){try{const r=await fetch('/api/dashboard?ts='+Date.now(),{cache:'no-store'}),j=await r.json();if(!r.ok)throw new Error(j.error);setP(j);setLast(new Date());setError('')}catch(e){setError(e.message)}}
 useEffect(()=>{load();const id=setInterval(load,REFRESH_MS);return()=>clearInterval(id)},[]);
 const rows=useMemo(()=>p?.rows.filter(r=>(f.province==='All'||r.province===f.province)&&(f.status==='All'||r.status===f.status)&&(f.rfo==='All'||r.rfo===f.rfo)&&(f.concern==='All'||r.concern===f.concern))||[],[p,f]);
 const m=useMemo(()=>{const group=(k,n=12)=>Object.entries(rows.reduce((a,r)=>{const x=r[k]||'Unspecified';a[x]=(a[x]||0)+1;return a},{})).sort((a,b)=>b[1]-a[1]).slice(0,n).map(([name,value])=>({name,value}));const volume=Object.entries(rows.reduce((a,r)=>{if(r.endorsedDate)a[r.endorsedDate.slice(0,7)]=(a[r.endorsedDate.slice(0,7)]||0)+1;return a},{})).sort().map(([date,count])=>({date,count}));return{count:rows.length,open:rows.filter(r=>r.open).length,beyond:rows.filter(r=>r.sla==='3. beyond 48 hrs').length,restored24:rows.filter(r=>r.restored24).length,new24:rows.filter(r=>r.new24).length,noRfo:rows.filter(r=>!r.rfo||r.rfo==='Blank').length,status:group('status',8),province:group('province',10),rfo:group('rfo',10),sla:group('sla',5),volume}},[rows]);
 const o=p?.options||{province:[],status:[],rfo:[],concern:[]}; const sourcePending=p?.quality?.rawPendingCount??p?.statusCounts?.PENDING??0;
 return <main><header className="top"><div><h1>NAP NOC LIVE MONITORING</h1><p>Operational status • SLA exposure • outage concentration • action queue</p></div><div className="live"><span/> LIVE • MONITORING</div></header>
 {error&&<div className="error">{error}</div>}<div className="filters"><Select label="PROVINCE" value={f.province} onChange={v=>setF({...f,province:v})} options={o.province}/><Select label="FINAL STATUS" value={f.status} onChange={v=>setF({...f,status:v})} options={o.status}/><Select label="RFO" value={f.rfo} onChange={v=>setF({...f,rfo:v})} options={o.rfo}/><Select label="CONCERN GROUP" value={f.concern} onChange={v=>setF({...f,concern:v})} options={o.concern}/></div>
 <div className="meta">Google Sheet published CSV live reader • NAP DOWN • {fmt(m.count)} records in current view • source PENDING count: {fmt(sourcePending)} • refreshed {last?last.toLocaleTimeString():'—'}</div>{f.province==='All'&&f.status==='All'&&f.rfo==='All'&&f.concern==='All'&&m.count!==sourcePending&&<div className="error">SOURCE RECONCILIATION: unfiltered NAP DOWN has {fmt(sourcePending)} PENDING rows but dashboard parsed {fmt(m.count)} records.</div>}
 <section className="agent"><div><strong>FORMULA SYNC AGENT</strong><span className={p?.quality?.agent?.status==='OK'?'agent-ok':'agent-warn'}>{p?.quality?.agent?.status||'CHECKING'}</span></div><div className="agent-checks">{(p?.quality?.agent?.checks||[]).map(x=><span key={x.name} title={x.detail}>{x.status==='OK'?'✓':'⚠'} {x.name}</span>)}</div><small>Checks the published NAP DOWN header map, 126-row source count, FINAL STATUS resolution, FINDINGS/RFO mapping, DATABASE concern mapping, and skipped rows.</small></section>
 <div className="cards"><Card title="TOTAL RECORDS" value={m.count} note="filtered dataset" accent="#20bff3"/><Card title="OPEN / ACTIONABLE" value={m.open} note="non-terminal status" accent="#ff637d"/><Card title="OPEN >48 HOURS" value={m.beyond} note="calculated elapsed time" accent="#ffb000"/><Card title="RESTORED LAST 24H" value={m.restored24} note="source DATE RESTORED" accent="#2ee3a1"/><Card title="NEW LAST 24H" value={m.new24} note="source TIMESTAMP / DATE ENDORSED" accent="#9d7cff"/><Card title="UNASSIGNED / NO RFO" value={m.noRfo} note="data-quality category" accent="#ff637d"/></div>
 <div className="grid two"><Panel title="Incident volume by endorsement date" subtitle="Derived from TIMESTAMP / DATE ENDORSED"><div className="chart"><ResponsiveContainer width="100%" height={250}><AreaChart data={m.volume}><defs><linearGradient id="g" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#22b8f2" stopOpacity=".35"/><stop offset="100%" stopColor="#22b8f2" stopOpacity=".03"/></linearGradient></defs><CartesianGrid stroke="#1a2940" vertical={false}/><XAxis dataKey="date" stroke="#71829d"/><YAxis stroke="#71829d"/><Tooltip contentStyle={{background:'#0c1628',border:'1px solid #23334f'}}/><Area type="monotone" dataKey="count" stroke="#27baf3" fill="url(#g)" strokeWidth={3}/></AreaChart></ResponsiveContainer></div></Panel><Panel title="Status distribution" subtitle="FINAL STATUS normalized from source records"><Donut data={m.status} colors={['#ff667d','#2ee3a1','#9d7cff','#22b8f2','#ffb000']}/></Panel></div>
 <div className="grid three"><Panel title="Open incidents by province" subtitle="NOC action volume per province"><ResponsiveContainer width="100%" height={280}><BarChart layout="vertical" data={m.province} margin={{left:30,right:20}}><CartesianGrid stroke="#1a2940" horizontal={false}/><XAxis type="number" stroke="#71829d"/><YAxis type="category" dataKey="name" width={105} stroke="#9aa8bd" tick={{fontSize:11}}/><Tooltip contentStyle={{background:'#0c1628',border:'1px solid #23334f'}}/><Bar dataKey="value" fill="#31b9ef" radius={[0,4,4,0]}/></BarChart></ResponsiveContainer></Panel><Panel title="Open incidents by RFO" subtitle="Blank RFO is retained as a data-quality category"><ResponsiveContainer width="100%" height={280}><BarChart layout="vertical" data={m.rfo} margin={{left:30,right:20}}><CartesianGrid stroke="#1a2940" horizontal={false}/><XAxis type="number" stroke="#71829d"/><YAxis type="category" dataKey="name" width={105} stroke="#9aa8bd" tick={{fontSize:10}}/><Tooltip contentStyle={{background:'#0c1628',border:'1px solid #23334f'}}/><Bar dataKey="value" fill="#9d7cff" radius={[0,4,4,0]}/></BarChart></ResponsiveContainer></Panel><Panel title="SLA exposure" subtitle="NOC SLA uses elapsed hours"><Donut data={m.sla} colors={['#2ee3a1','#ffb000','#ff667d']}/></Panel></div>
 <footer><span>Data quality agent: {p?.quality?.issues??0} issues • header row: {p?.quality?.headerRow??'—'} • source rows: {fmt(p?.quality?.sourceRows??0)} • parsed: {fmt(p?.quality?.parsedRows??0)} • dropped blank rows: {fmt(p?.quality?.droppedRows??0)} • raw PENDING: {fmt(p?.quality?.rawPendingCount??0)}</span><span>Auto refresh: 60 seconds</span></footer></main>
}
