'use client';
import {useCallback,useEffect,useMemo,useState} from 'react';
import {AreaChart,Area,BarChart,Bar,PieChart,Pie,Cell,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer} from 'recharts';
const REFRESH_MS=3000;
const fmt=n=>new Intl.NumberFormat('en-US').format(Number(n)||0);
const hBetween=(s,now=Date.now())=>{const d=new Date(s||'');if(!s||Number.isNaN(d.getTime()))return null;return Math.max(0,(now-d.getTime())/36e5)};
const dur=h=>{if(h==null)return '—';const d=Math.floor(h/24),r=Math.floor(h%24),m=Math.floor((h%1)*60);return d?d+'d '+r+'h':r?r+'h '+m+'m':m+'m'};
function Select({label,value,onChange,options}){return <label className="filter"><span>{label}</span><select value={value} onChange={e=>onChange(e.target.value)}><option>All</option>{(options||[]).map(v=><option key={v}>{v}</option>)}</select></label>}
function Card({title,value,note,accent}){return <div className="card" style={{'--accent':accent}}><div className="card-label">{title}</div><div className="card-value">{typeof value==='number'?fmt(value):value}</div><div className="card-note">{note}</div></div>}
function Panel({title,subtitle,children}){return <section className="panel"><div className="panel-head"><h2>{title}</h2><p>{subtitle}</p></div>{children}</section>}
function Donut({data,colors}){return <div className="chart-wrap"><ResponsiveContainer width="100%" height={250}><PieChart><Pie data={data} dataKey="value" nameKey="name" innerRadius={58} outerRadius={88} paddingAngle={2}>{data.map((_,i)=><Cell key={i} fill={colors[i%colors.length]}/>)}</Pie><Tooltip contentStyle={{background:'#0c1628',border:'1px solid #23334f'}}/></PieChart></ResponsiveContainer><div className="legend">{data.map((x,i)=><div key={x.name}><i style={{background:colors[i%colors.length]}}/>{x.name}<b>{fmt(x.value)}</b></div>)}</div></div>}
export default function Dashboard(){
 const [p,setP]=useState(null),[f,setF]=useState({province:'All',status:'All',finding:'All',rfo:'All',concern:'All',view:'pending'}),[version,setVersion]=useState(''),[last,setLast]=useState(null),[error,setError]=useState(''),[tick,setTick]=useState(Date.now()),[agent,setAgent]=useState(null);
 const load=useCallback(async v=>{const r=await fetch('/api/snapshot?version='+encodeURIComponent(v||'')+'&ts='+Date.now(),{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'Snapshot error');setP(j);setVersion(j.version||v);setLast(new Date())},[]);
 const check=useCallback(async()=>{try{const r=await fetch('/api/meta?ts='+Date.now(),{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'Meta error');setAgent(j.agent||null);if(!version||j.version!==version)await load(j.version);else setLast(new Date());setError('')}catch(e){setError(e.message)}},[version,load]);
 useEffect(()=>{check();const id=setInterval(()=>{setTick(Date.now());if(!document.hidden)check()},REFRESH_MS);return()=>clearInterval(id)},[check]);
 const rows=p?.rows||[],opt=p?.options||{};
 const filtered=useMemo(()=>rows.filter(r=>(f.province==='All'||r.province===f.province)&&(f.status==='All'||r.status===f.status)&&(f.finding==='All'||r.finding===f.finding)&&(f.rfo==='All'||r.rfo===f.rfo)&&(f.concern==='All'||r.concern===f.concern)).filter(r=>f.view==='all'||f.view==='pending'&&r.status==='PENDING'||f.view==='open'&&r.open||f.view==='over48'&&r.open&&((hBetween(r.dateEndorsed,tick)||0)>48)),[rows,f,tick]);
 const pending=rows.filter(r=>r.status==='PENDING'),open=rows.filter(r=>r.open),restored=rows.filter(r=>r.status==='RESTORED'),over48=open.filter(r=>(hBetween(r.dateEndorsed,tick)||0)>48),new24=rows.filter(r=>{const h=hBetween(r.dateEndorsed,tick);return h!=null&&h<=24}),rest24=restored.filter(r=>{const h=hBetween(r.dateRestored,tick);return h!=null&&h<=24});
 const avgDown=pending.length?pending.reduce((s,r)=>s+(hBetween(r.dateEndorsed,tick)||0),0)/pending.length:null,avgUp=restored.length?restored.reduce((s,r)=>s+(hBetween(r.dateRestored,tick)||0),0)/restored.length:null;
 const statusData=Object.entries(p?.statusCounts||{}).sort((a,b)=>b[1]-a[1]).map(([name,value])=>({name,value}));const statusColors=['#ff667d','#2ee3a1','#9d7cff','#22b8f2','#ffb000','#f97316','#60a5fa','#94a3b8','#e879f9','#c084fc','#34d399','#fb7185'];
 const trend=useMemo(()=>{const m={};filtered.forEach(r=>{const d=new Date(r.dateEndorsed);if(!Number.isNaN(d.getTime())){const k=d.toISOString().slice(0,10);m[k]=(m[k]||0)+1}});return Object.keys(m).sort().slice(-31).map(k=>({date:k,count:m[k]}))},[filtered]);
 const province=useMemo(()=>{const m={};pending.forEach(r=>m[r.province]=(m[r.province]||0)+1);return Object.entries(m).sort((a,b)=>b[1]-a[1]).slice(0,10).map(([name,value])=>({name,value}))},[pending]);
 const findings=useMemo(()=>{const m={};pending.forEach(r=>{const k=r.finding||'Blank';m[k]=(m[k]||0)+1});return Object.entries(m).sort((a,b)=>b[1]-a[1]).slice(0,10).map(([name,value])=>({name,value}))},[pending]);
 const downProv=useMemo(()=>{const sum={},cnt={};pending.forEach(r=>{const h=hBetween(r.dateEndorsed,tick);if(h==null)return;sum[r.province]=(sum[r.province]||0)+h;cnt[r.province]=(cnt[r.province]||0)+1});return Object.entries(sum).map(([name,v])=>({name,value:Number((v/(cnt[name]||1)/24).toFixed(1))})).sort((a,b)=>b.value-a.value).slice(0,10)},[pending,tick]);
 const queue=[...(p?.napDownRows?.length?p.napDownRows:filtered)].sort((a,b)=>(Number(b.status==='PENDING')-Number(a.status==='PENDING'))||((b.downHours||0)-(a.downHours||0)));
 async function agentAction(action){const token=window.prompt('NOC_AGENT_TOKEN');if(!token)return;try{const r=await fetch('/api/agent',{method:'POST',headers:{'Content-Type':'application/json','x-noc-agent-token':token},body:JSON.stringify({action})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Agent error');alert(action==='repair'?'Safe repair completed: '+(j.repairedRuns||0)+' runs.':'Formula audit completed: '+(j.issues?.length||0)+' issues.');check()}catch(e){alert(e.message)}}
 return <main>
  <header className="top"><div><h1>NAP NOC LIVE MONITORING</h1><p>Google Sheet synchronized • 3s version check • live outage status • downtime / uptime • formula & data-quality agent</p></div><div className="live"><span/> LIVE • {last?last.toLocaleTimeString():'CONNECTING'}</div></header>
  {error&&<div className="error">{error}</div>}
  <div className="filters">
   <Select label="PROVINCE" value={f.province} onChange={v=>setF({...f,province:v})} options={opt.province}/>
   <Select label="STATUS" value={f.status} onChange={v=>setF({...f,status:v})} options={opt.status}/>
   <Select label="FINDINGS / NAP STATUS" value={f.finding} onChange={v=>setF({...f,finding:v})} options={opt.finding}/>
   <Select label="RFO" value={f.rfo} onChange={v=>setF({...f,rfo:v})} options={opt.rfo}/>
   <Select label="CONCERN GROUP" value={f.concern} onChange={v=>setF({...f,concern:v})} options={opt.concern}/>
   <Select label="NOC VIEW" value={f.view} onChange={v=>setF({...f,view:v})} options={['pending','open','over48','all']}/>
  </div>
  <div className="meta">Version: {version||'—'} • DATABASE rows: {fmt(rows.length)} • <b>NAP DOWN / PENDING: {fmt(p?.pendingCount||0)}</b> • source: {p?.sourceMode||'—'} • refresh check: {REFRESH_MS/1000}s</div>
  <div className="cards">
   <Card title="NAP DOWN / PENDING" value={pending.length} note="exact STATUS = PENDING" accent="#ff667d"/><Card title="OPEN / ACTIONABLE" value={open.length} note="non-terminal status" accent="#ffb000"/><Card title="OPEN >48 HOURS" value={over48.length} note="live elapsed down time" accent="#fb7185"/><Card title="RESTORED" value={restored.length} note="STATUS = RESTORED" accent="#2ee3a1"/><Card title="NEW LAST 24H" value={new24.length} note="DATE ENDORSED" accent="#9d7cff"/><Card title="RESTORED LAST 24H" value={rest24.length} note="DATE RESTORED" accent="#22b8f2"/><Card title="AVG CURRENT DOWN TIME" value={dur(avgDown)} note="PENDING cases" accent="#ff667d"/><Card title="AVG UP TIME SINCE RESTORE" value={dur(avgUp)} note="RESTORED cases" accent="#2ee3a1"/><Card title="MISSING RFO" value={open.filter(r=>!r.rfo).length} note="open records" accent="#f97316"/><Card title="SOURCE ROWS" value={rows.length} note="live DATABASE" accent="#22b8f2"/>
  </div>
  <section className="status-board">{statusData.map((x,i)=><div className="status-pill" key={x.name}><span style={{background:statusColors[i%statusColors.length]}}/>{x.name}<b>{fmt(x.value)}</b></div>)}</section>
  <div className="grid two"><Panel title="Incident volume by endorsement date" subtitle="Filtered view"><div className="chart"><ResponsiveContainer width="100%" height={250}><AreaChart data={trend}><CartesianGrid stroke="#1a2940" vertical={false}/><XAxis dataKey="date" stroke="#71829d"/><YAxis stroke="#71829d"/><Tooltip contentStyle={{background:'#0c1628',border:'1px solid #23334f'}}/><Area type="monotone" dataKey="count" stroke="#27baf3" fill="#22b8f233" strokeWidth={3}/></AreaChart></ResponsiveContainer></div></Panel><Panel title="All status distribution" subtitle="All source statuses counted"><Donut data={statusData} colors={statusColors}/></Panel></div>
  <div className="grid three"><Panel title="NAP DOWN by province" subtitle="PENDING only"><ResponsiveContainer width="100%" height={280}><BarChart layout="vertical" data={province}><CartesianGrid stroke="#1a2940" horizontal={false}/><XAxis type="number" stroke="#71829d"/><YAxis type="category" dataKey="name" width={110} stroke="#9aa8bd"/><Tooltip contentStyle={{background:'#0c1628',border:'1px solid #23334f'}}/><Bar dataKey="value" fill="#31b9ef" radius={[0,4,4,0]}/></BarChart></ResponsiveContainer></Panel><Panel title="Top findings / NAP Status" subtitle="PENDING only"><ResponsiveContainer width="100%" height={280}><BarChart layout="vertical" data={findings}><CartesianGrid stroke="#1a2940" horizontal={false}/><XAxis type="number" stroke="#71829d"/><YAxis type="category" dataKey="name" width={125} stroke="#9aa8bd" tick={{fontSize:10}}/><Tooltip contentStyle={{background:'#0c1628',border:'1px solid #23334f'}}/><Bar dataKey="value" fill="#9d7cff" radius={[0,4,4,0]}/></BarChart></ResponsiveContainer></Panel><Panel title="Average live downtime by province" subtitle="PENDING • days"><ResponsiveContainer width="100%" height={280}><BarChart layout="vertical" data={downProv}><CartesianGrid stroke="#1a2940" horizontal={false}/><XAxis type="number" stroke="#71829d"/><YAxis type="category" dataKey="name" width={110} stroke="#9aa8bd"/><Tooltip contentStyle={{background:'#0c1628',border:'1px solid #23334f'}} formatter={v=>[v+' days','avg down']}/><Bar dataKey="value" fill="#ff667d" radius={[0,4,4,0]}/></BarChart></ResponsiveContainer></Panel></div>
  <section className="agent"><div className="agent-head"><div><strong>FORMULA / DATA-QUALITY AGENT</strong> <span className={agent?.configured?'agent-ok':'agent-warn'}>{agent?.configured?'READY':'CONFIG NEEDED'}</span></div><div className="agent-actions"><button onClick={()=>agentAction('audit')}>Audit formulas</button><button onClick={()=>agentAction('repair')}>Repair safe formula gaps</button></div></div><div className="agent-checks"><span>Exact A1 formulas from live sheet</span><span>Derived columns only</span><span>Manual fields protected</span><span>Last audit: {agent?.lastAudit?new Date(agent.lastAudit).toLocaleString():'—'}</span></div></section>
  <section className="panel action-panel"><div className="panel-head"><h2>Action Queue — NAP DOWN / Selected View</h2><p>Findings • NAP Code • Down Time • Up Time • RFO • OSP • ETR</p></div><div className="table-wrap"><table><thead><tr><th>Down Time</th><th>Status</th><th>Province</th><th>Municipality</th><th>Barangay</th><th>NAP Code</th><th>Findings</th><th>RFO</th><th>Up Time</th><th>OSP</th><th>Endorsed</th><th>Restored</th><th>ETR</th></tr></thead><tbody>{queue.slice(0,600).map((r,i)=><tr key={(r.sourceRow||r.rowNumber||i)+'-'+(r.napCode||'')}><td>{dur(r.downHours!=null?r.downHours:hBetween(r.dateEndorsed,tick))}</td><td><span className={'badge '+(r.status==='PENDING'?'bad':'warn')}>{r.status||'BLANK'}</span></td><td>{r.province||'—'}</td><td>{r.municipality||'—'}</td><td>{r.barangay||'—'}</td><td>{r.napCode||r.facility||'—'}</td><td>{r.finding||'—'}</td><td>{r.rfo||'—'}</td><td>{r.dateRestored?dur(r.upHours!=null?r.upHours:hBetween(r.dateRestored,tick)):'DOWN'}</td><td>{r.ospTeam||'—'}</td><td>{r.dateEndorsed?new Date(r.dateEndorsed).toLocaleString():'—'}</td><td>{r.dateRestored?new Date(r.dateRestored).toLocaleString():'—'}</td><td>{r.etr||'—'}</td></tr>)}</tbody></table></div></section>
  <footer><span>Formula agent issues: {agent?.issues??'—'} • pending count is live STATUS=PENDING • downtime updates locally between syncs</span><span>3s meta check • full spreadsheet sync only on source version change</span></footer>
 </main>
}
