const {google}=require('googleapis');
const CFG={sheetId:process.env.GOOGLE_SHEET_ID||'1yhtm8pTJ9VP0TUrFm2JedYoCZ_M22K196luw3u9Xl4s',dbGid:process.env.GOOGLE_SHEET_GID_DATABASE||'946404240',napGid:process.env.GOOGLE_SHEET_GID_NAP_DOWN||'1995500191',publishedId:process.env.GOOGLE_PUBLISHED_ID||'2PACX-1vSKPMOn6CXZN3xn1zyKGcDyayAHLMuntjJ137x5dWxZzoJstX3Ef_XTtAgh6zId4n1gEyQBeL91lHFi'};
const configured=()=>Boolean(process.env.GOOGLE_SERVICE_ACCOUNT_JSON_BASE64);
function auth(){let c;try{c=JSON.parse(Buffer.from(process.env.GOOGLE_SERVICE_ACCOUNT_JSON_BASE64,'base64').toString('utf8'))}catch(e){throw new Error('Invalid GOOGLE_SERVICE_ACCOUNT_JSON_BASE64')};return new google.auth.GoogleAuth({credentials:c,scopes:['https://www.googleapis.com/auth/spreadsheets','https://www.googleapis.com/auth/drive.readonly']})}
async function clients(){const a=auth();return{sheets:google.sheets({version:'v4',auth:a}),drive:google.drive({version:'v3',auth:a})}}
function col(n){let s='';while(n>0){const r=(n-1)%26;s=String.fromCharCode(65+r)+s;n=Math.floor((n-1)/26)}return s}
async function tabs(){const {sheets}=await clients();const r=await sheets.spreadsheets.get({spreadsheetId:CFG.sheetId,includeGridData:false,fields:'sheets(properties(sheetId,title,gridProperties(rowCount,columnCount)))'});return r.data.sheets||[]}
async function tab(gid){const t=(await tabs()).find(x=>String(x.properties.sheetId)===String(gid));if(!t)throw new Error('Sheet GID '+gid+' not found');return t.properties}
async function values(gid,render='FORMATTED_VALUE'){const t=await tab(gid),{sheets}=await clients(),rows=Number(t.gridProperties?.rowCount||1000),cols=Math.min(Number(t.gridProperties?.columnCount||40),100),range="'"+String(t.title).replace(/'/g,"''")+"'!A1:"+col(cols)+rows;const r=await sheets.spreadsheets.values.get({spreadsheetId:CFG.sheetId,range,majorDimension:'ROWS',valueRenderOption:render,dateTimeRenderOption:'FORMATTED_STRING'});return{properties:t,values:r.data.values||[]}}
function csv(text){const out=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&q&&n==='"'){cell+='"';i++;continue}if(c==='"'){q=!q;continue}if(c===','&&!q){row.push(cell);cell='';continue}if((c==='\\n'||c==='\\r')&&!q){if(c==='\\r'&&n==='\\n')i++;row.push(cell);cell='';if(row.some(v=>String(v).trim()!==''))out.push(row);row=[];continue}cell+=c}if(cell!==''||row.length){row.push(cell);if(row.some(v=>String(v).trim()!==''))out.push(row)}return out}
async function published(gid){const u='https://docs.google.com/spreadsheets/d/e/'+CFG.publishedId+'/pub?gid='+gid+'&single=true&output=csv&cachebust='+Date.now();const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw new Error('Published CSV HTTP '+r.status);const t=await r.text();if(/<html|<!doctype/i.test(t))throw new Error('Published sheet returned HTML');return{properties:{sheetId:Number(gid),title:'GID '+gid},values:csv(t)}}
async function source(gid){return configured()?values(gid):published(gid)}
async function version(){if(configured()){const {drive}=await clients();const r=await drive.files.get({fileId:CFG.sheetId,fields:'modifiedTime'});return String(r.data.modifiedTime||Date.now())}return 'published-'+Math.floor(Date.now()/10000)}
module.exports={CFG,configured,clients,tabs,tab,values,source,version};
